name: suis_message
description: A Suis Inc. Messaging Experience
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  dynamic_color: ^1.6.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  go_router: ^10.0.0
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
  fonts:
    - family: RobotoBlack
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
    - family: RobotoBlackItalic
      fonts:
        - asset: assets/fonts/Roboto-BlackItalic.ttf
    - family: RobotoBold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: RobotoBoldItalic
      fonts:
        - asset: assets/fonts/Roboto-BoldItalic.ttf
    - family: RobotoItalic
      fonts:
        - asset: assets/fonts/Roboto-Italic.ttf
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: RobotoLightItalic
      fonts:
        - asset: assets/fonts/Roboto-LightItalic.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: RobotoMediumItalic
      fonts:
        - asset: assets/fonts/Roboto-MediumItalic.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: RobotoThin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
    - family: RobotoThinItalic
      fonts:
        - asset: assets/fonts/Roboto-ThinItalic.ttf

